name: proxyman_flutter
description: "A Proxyman-like network debugging proxy tool built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Network and HTTP handling
  http: ^1.1.0
  # UI components
  flutter_staggered_grid_view: ^0.7.0
  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 