name: proxyman_flutter
description: "A Proxyman-like network debugging proxy tool built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Network and HTTP handling
  http: ^1.1.0
  dio: ^5.3.2
  # Proxy functionality
  shelf_proxy: ^1.0.4  # Replaced with null-safe alternative
  shelf: ^1.4.1  # Added for proxy server functionality
  # UI components
  flutter_staggered_grid_view: ^0.7.0
  data_table_2: ^2.5.10
  # State management
  provider: ^6.1.1
  # JSON handling
  json_annotation: ^4.8.1
  # File handling
  path_provider: ^2.1.1
  # Time formatting
  intl: ^0.18.1
  # Network info
  network_info_plus: ^4.1.0
  # Permissions
  permission_handler: ^11.0.1
  # Certificate generation
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  # URL handling
  url_launcher: ^6.2.1
  # QR code generation
  qr_flutter: ^4.1.0
  # Clipboard functionality
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true 